Fix: Property 'mockReturnValue' does not exist on type ...
eratio08/vitest-mock-extended pull request #511
Opened 2024-07-12 13:35 UTC by Gabrielbdd

This is my first contribution and I'm not a typescript wizard :D, so feel free to check whether my changes makes sense.

The problem was that Vitest `Mock` receives only one generic argument, but 2 were being provided.
I checked what it were expecting, and it happened to be the exact definition as the `FallbackImplementation` on the project, so I just used it.

Besides that, a test as breaking because it was assuming the host machine would be on the UTC timezone. I fixed it by creating the date using the unix timestamp, not sure if it is a good way. It can also be solved by setting the `TZ` env variable.

This PR closes the issue #508

2024-07-12 15:55 UTC, WolfSoko approved these changes

2024-07-12 15:56 UTC, WolfSoko commented
I'm not the owner, but I'm facing the same issue and I think the PR looks good! ✅

2024-07-15 06:30 UTC, eratio08 commented
Thanks for your contribution @Gabrielbdd, looks good to me! Could you take a look at the failing test, will merge & publish this when the test is green!

2024-07-15 06:33 UTC, eratio08 approved these changes

2024-07-15 19:19 UTC, eratio08 commented on src/Mock.spec.ts
> +      const mockObj = mock<objWithDate>({ date: new Date(unixTimestamp) })
I guess you could try, which also seems to work for me locally
```suggestion
      const unixTimestamp = Date.parse("15 Jan 2000 00:00:00 UTC"))
      const mockObj = mock<objWithDate>({ date: new Date(unixTimestamp) })
```

2024-07-15 19:28 UTC, eratio08 requested changes
Only the failing test

2024-07-15 19:33 UTC, eratio08 commented
I will take your change anyway and will fix the test, thx for your help!

2024-07-15 19:34 UTC, merged